### ISSUE TITLE
Please let the developer know. All items in list are Metadata/Items/Flasks

### ISSUE THREAD

**Issue by danthespal** [zaafar/GameOverlay#218]
Error.log v0.343 [Build with VS2022]

```
15/05/2022 00:09 Program exited with message:
 System.Exception: New (IsValid=True) flask base found Ornate Mace. Please let the developer know. All items in list are Metadata/Items/Flasks/FlaskLife12 Metadata/Items/Flasks/FlaskUtility5 Metadata/Items/Flasks/FlaskUtility10 Metadata/Items/Flasks/FlaskUtility9 Metadata/Items/Flasks/FlaskUtility6 
   at AutoHotKeyTrigger.ProfileManager.Conditions.FlaskEffectCondition.Evaluate() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Conditions\FlaskEffectCondition.cs:line 97
   at AutoHotKeyTrigger.ProfileManager.Rule.<>c.<Evaluate>b__16_0(ICondition x) in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 184
   at System.Collections.Generic.List`1.TrueForAll(Predicate`1 match)
   at AutoHotKeyTrigger.ProfileManager.Rule.Evaluate() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 184
   at AutoHotKeyTrigger.ProfileManager.Rule.Execute(Action`1 logger) in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 134
   at AutoHotKeyTrigger.AutoHotKeyTriggerCore.DrawUI() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\AutoHotKeyTriggerCore.cs:line 195
   at PoEOverlay.Plugin.PManager.DrawPluginUiRenderCoroutine()+MoveNext() in D:\Tools\PoEOverlay\PoEOverlay\Plugin\PManager.cs:line 201
   at Coroutine.ActiveCoroutine.MoveNext()
   at Coroutine.ActiveCoroutine.OnEvent(Event evt)
   at Coroutine.CoroutineHandlerInstance.RaiseEvent(Event evt)
   at Coroutine.CoroutineHandler.RaiseEvent(Event evt)
   at PoEOverlay.GameOverlay.Render() in D:\Tools\PoEOverlay\PoEOverlay\GameOverlay.cs:line 78
   at ClickableTransparentOverlay.Overlay.RunInfiniteLoop(CancellationToken cancellationToken)
   at ClickableTransparentOverlay.Overlay.<Start>b__20_0()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
------------------------------
15/05/2022 01:55 Program exited with message:
 System.Exception: New (IsValid=True) flask base found Slaughter Knife. Please let the developer know. All items in list are Metadata/Items/Flasks/FlaskUtility6 Metadata/Items/Flasks/FlaskUtility9 Metadata/Items/Flasks/FlaskUtility5 Metadata/Items/Flasks/FlaskLife12 Metadata/Items/Flasks/FlaskUtility10 
   at AutoHotKeyTrigger.ProfileManager.Conditions.FlaskEffectCondition.Evaluate() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Conditions\FlaskEffectCondition.cs:line 97
   at AutoHotKeyTrigger.ProfileManager.Rule.<>c.<Evaluate>b__16_0(ICondition x) in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 184
   at System.Collections.Generic.List`1.TrueForAll(Predicate`1 match)
   at AutoHotKeyTrigger.ProfileManager.Rule.Evaluate() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 184
   at AutoHotKeyTrigger.ProfileManager.Rule.Execute(Action`1 logger) in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 134
   at AutoHotKeyTrigger.AutoHotKeyTriggerCore.DrawUI() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\AutoHotKeyTriggerCore.cs:line 195
   at PoEOverlay.Plugin.PManager.DrawPluginUiRenderCoroutine()+MoveNext() in D:\Tools\PoEOverlay\PoEOverlay\Plugin\PManager.cs:line 201
   at Coroutine.ActiveCoroutine.MoveNext()
   at Coroutine.ActiveCoroutine.OnEvent(Event evt)
   at Coroutine.CoroutineHandlerInstance.RaiseEvent(Event evt)
   at Coroutine.CoroutineHandler.RaiseEvent(Event evt)
   at PoEOverlay.GameOverlay.Render() in D:\Tools\PoEOverlay\PoEOverlay\GameOverlay.cs:line 78
   at ClickableTransparentOverlay.Overlay.RunInfiniteLoop(CancellationToken cancellationToken)
   at ClickableTransparentOverlay.Overlay.<Start>b__20_0()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
------------------------------
15/05/2022 02:10 Program exited with message:
 System.Exception: New (IsValid=True) flask base found Field Lamellar. Please let the developer know. All items in list are Metadata/Items/Flasks/FlaskUtility9 Metadata/Items/Flasks/FlaskUtility5 Metadata/Items/Flasks/FlaskLife12 Metadata/Items/Flasks/FlaskUtility6 Metadata/Items/Flasks/FlaskUtility10 
   at AutoHotKeyTrigger.ProfileManager.Conditions.FlaskEffectCondition.Evaluate() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Conditions\FlaskEffectCondition.cs:line 97
   at AutoHotKeyTrigger.ProfileManager.Rule.<>c.<Evaluate>b__16_0(ICondition x) in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 184
   at System.Collections.Generic.List`1.TrueForAll(Predicate`1 match)
   at AutoHotKeyTrigger.ProfileManager.Rule.Evaluate() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 184
   at AutoHotKeyTrigger.ProfileManager.Rule.Execute(Action`1 logger) in D:\Tools\PoEOverlay\AutoHotKeyTrigger\ProfileManager\Rule.cs:line 134
   at AutoHotKeyTrigger.AutoHotKeyTriggerCore.DrawUI() in D:\Tools\PoEOverlay\AutoHotKeyTrigger\AutoHotKeyTriggerCore.cs:line 195
   at PoEOverlay.Plugin.PManager.DrawPluginUiRenderCoroutine()+MoveNext() in D:\Tools\PoEOverlay\PoEOverlay\Plugin\PManager.cs:line 201
   at Coroutine.ActiveCoroutine.MoveNext()
   at Coroutine.ActiveCoroutine.OnEvent(Event evt)
   at Coroutine.CoroutineHandlerInstance.RaiseEvent(Event evt)
   at Coroutine.CoroutineHandler.RaiseEvent(Event evt)
   at PoEOverlay.GameOverlay.Render() in D:\Tools\PoEOverlay\PoEOverlay\GameOverlay.cs:line 78
   at ClickableTransparentOverlay.Overlay.RunInfiniteLoop(CancellationToken cancellationToken)
   at ClickableTransparentOverlay.Overlay.<Start>b__20_0()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
------------------------------
```

**Comment by zaafar** [comment]
How often is this happening?

**Comment by danthespal** [comment]
> How often is this happening?

Every time I start it, so I disable for now AutoHotKey

**Comment by zaafar** [comment]
Hmm, weird. Maybe try restarting the computer and re-download the GH from scratch in a new folder.

**Comment by danthespal** [comment]
idk why, but it solved
